export const REASONS_DEFS = {
  def_isosceles: {
    name: "def_isosceles",
    title: "Def. Isosceles Triangle",
    body: "An isosceles triangle is a triangle with two congruent sides.",
    dependencies: ["con_seg"],
    conclusion: "isosceles",
  },
  sas: {
    name: "sas",
    title: "SAS Triangle Congruence",
    body: "Side-Angle-Side (SAS) Congruence. If two sides and the included angle of each triangle are congruent to each other, then the triangles are congruent.",
    dependencies: [
      "con_seg_ref_allow",
      "con_ang_ref_allow",
      "con_seg_ref_allow",
    ],
    conclusion: "con_tri",
  },
  sss: {
    name: "sss",
    title: "SSS Triangle Congruence",
    body: "Side-Side-Side (SSS) Triangle Congruence. If two triangles have three sides that are congruent to each other, then the triangles are congruent.",
    dependencies: [
      "con_seg_ref_allow",
      "con_seg_ref_allow",
      "con_seg_ref_allow",
    ],
    conclusion: "con_tri",
  },
  asa: {
    name: "asa",
    title: "ASA Triangle Congruence",
    body: "Angle-Side-Angle (ASA) Triangle Congruence. If two triangles have two congruent angles and one included congruent side, then the triangles are congruent.",
    dependencies: [
      "con_ang_ref_allow",
      "con_seg_ref_allow",
      "con_ang_ref_allow",
    ],
    conclusion: "con_tri",
  },
  aas: {
    name: "aas",
    title: "AAS Triangle Congruence",
    body: "Angle-Angle-Side (AAS) Triangle Congruence. If a pair of triangles have two angles and one adjacent side that are congruent to each other, then the triangles are congruent.",
    dependencies: [
      "con_ang_ref_allow",
      "con_ang_ref_allow",
      "con_seg_ref_allow",
    ],
    conclusion: "con_tri",
  },
  rhl: {
    name: "rhl",
    title: "RHL Triangle Congruence",
    body: "Right-Hypotenuse-Leg (RHL) Triangle Congruence. If two right triangles have a hypotenuse and a leg that are congruent to each other, then the triangles are congruent.",
    dependencies: ["con_right", "con_seg_ref_allow", "con_seg_ref_allow"],
    conclusion: "con_tri",
  },
  cpctc: {
    name: "cpctc",
    title: "CPCTC",
    body: "Corresponding Parts of Congruent Triangles are Congruent (CPCTC). If two triangles are congruent, then their corresponding angles and sides are also congruent.",
    dependencies: ["con_tri"],
    conclusion: "con_seg, con_ang",
  },
  reflex: {
    name: "reflex",
    title: "Reflexive Property",
    body: "Any geometric figure is congruent with itself.",
    dependencies: [],
    conclusion: "ref_seg, ref_ang",
  },
  def_perp: {
    name: "def_perp",
    title: "Def. Perpendicular Lines",
    body: "If two lines meet at 90°, then they are perpendicular.",
    dependencies: ["right"],
    conclusion: "perp",
  },
  def_midpt: {
    name: "def_midpt",
    title: "Def. Midpoint",
    body: "The point that is halfway between two endpoints of a segment.",
    dependencies: ["midpt"],
    conclusion: "con_seg",
  },
  midpt_conv: {
    name: "midpt_conv",
    title: "Def. Midpoint (Converse)",
    body: "If two subsections of a line are congruent, then the point dividing those subsections is the midpoint.",
    dependencies: ["con_seg"],
    conclusion: "midpt",
  },
  vert_ang: {
    name: "vert_ang",
    title: "Vertical Angles Theorem",
    body: "If two lines intersect then the angles that are opposite from each other are congruent.",
    diagramDependencies: ["intersect_seg"],
    dependencies: [],
    conclusion: "con_ang",
  },
  altint_conv: {
    name: "altint_conv",
    title: "Alternate Interior Angles (Converse)",
    body: "If a transversal (a line that crosses two or more lines) forms opposite interior angles that are congruent, then the two lines it intersects with are parallel to each other.",
    diagramDependencies: ["transversal"],
    dependencies: ["con_ang"],
    conclusion: "para",
  },
  altint: {
    name: "altint",
    title: "Alternate Interior Angles Theorem",
    body: "If two parallel lines are cut by a transversal (a line that crosses two or more lines), then the formed alternate interior angles are congruent.",
    diagramDependencies: ["transversal"],
    dependencies: ["para"],
    conclusion: "con_ang",
  },
  altext: {
    name: "altext",
    title: "Alternate Exterior Angles Theorem",
    body: "If two parallel lines are cut by a transversal (a line that crosses two or more lines), then the formed alternate exterior angles are congruent.",
    diagramDependencies: ["transversal"],
    dependencies: ["para"],
    conclusion: "con_ang",
  },
  altext_conv: {
    name: "altext_conv",
    title: "Alternate Exterior Angles (Converse)",
    body: "If a transversal (a line that crosses two or more lines) forms opposite exterior angles that are congruent, then the two lines it intersects with are parallel to each other.",
    diagramDependencies: ["transversal"],
    dependencies: ["con_ang"],
    conclusion: "para",
  },
  sameside_ang: {
    name: "sameside_ang",
    title: "Same Side Interior Angles Theorem",
    body: "If two parallel lines are cut by a transversal (a line that crosses two or more lines), then the formed same side interior angles are supplementary.",
    diagramDependencies: ["transversal"],
    dependencies: ["para"],
    conclusion: "supplementary",
  },
  sameside_ang_conv: {
    name: "sameside_ang_conv",
    title: "Same Side Interior Angles (Converse)",
    body: "If a transversal (a line that crosses two or more lines) forms same side interior angles that are supplementary, then the two lines it intersects with are parallel to each other.",
    diagramDependencies: ["transversal"],
    dependencies: ["supplementary"],
    conclusion: "para",
  },
  corresp_ang: {
    name: "corresp_ang",
    title: "Corresponding Angles",
    body: "If two parallel lines are cut by a transversal, then each pair of corresponding angles is congruent.",
    diagramDependencies: ["transversal"],
    dependencies: ["para"],
    conclusion: "con_ang",
  },
  corresp_ang_conv: {
    name: "corresp_ang_conv",
    title: "Corresponding Angles (Converse)",
    body: "If a transversal (a line that crosses two or more lines) forms corresponding angles that are congruent, then the two lines it intersects with are parallel to each other.",
    diagramDependencies: ["transversal"],
    dependencies: ["con_ang"],
    conclusion: "para",
  },
  def_ang_bisect: {
    name: "def_ang_bisect",
    title: "Def. Angle Bisector",
    body: "A line that splits an angle into two equal parts.",
    dependencies: ["ang_bisect"],
    conclusion: "con_ang",
  },
  ang_bisect_conv: {
    name: "ang_bisect_conv",
    title: "Def. Angle Bisector (Converse)",
    body: "If two adjacent angles are congruent, then the line that splits the angle is an angle bisector.",
    dependencies: ["con_ang"],
    conclusion: "ang_bisect",
  },
  def_con_right: {
    name: "def_con_right",
    title: "Congruent Right Angles",
    body: "Any two right angles are congruent (each measures 90°).",
    dependencies: ["right", "right"],
    conclusion: "con_ang, con_right",
  },
  perp_con_ang: {
    name: "perp_con_ang",
    title: "Perpendicular Adjacent Angles",
    body: "If two lines are perpendicular, then the formed adjacent angles are congruent. Each angle is 90°.",
    dependencies: ["perp"],
    conclusion: "con_ang, con_right",
  },
  rectangle: {
    name: "rectangle",
    title: "Def. Rectangle",
    body: "A rectangle is a type of parallelogram that has four right angles. The opposite sides of a rectangle are equal in length.",
    dependencies: ["rectangle"],
    conclusion: "con_right, con_ang, con_seg",
  },
  def_linear_pair: {
    name: "def_linear_pair",
    title: "Def. Linear Pair",
    body: "Two adjacent angles that form a straight line are a linear pair. The angles in a linear pair are supplementary.",
    dependencies: ["linear_pair"],
    conclusion: "supplementary",
  },
  linear_pair_conv: {
    name: "linear_pair_conv",
    title: "Def. Linear Pair (Converse)",
    body: "If two adjacent angles are supplementary, then they form a linear pair.",
    dependencies: ["supplementary"],
    conclusion: "linear_pair",
  },
  con_supplements: {
    name: "con_supplements",
    title: "Congruent Supplements",
    body: "If two angles are supplementary to congruent angles, then the two angles are congruent.",
    dependencies: ["supplementary", "supplementary", "con_ang"],
    conclusion: "con_ang",
  },
  con_supplements_same: {
    name: "con_supplements_same",
    title: "Congruent Supplements",
    body: "If two angles are supplementary to the same angle, then the two angles are congruent.",
    dependencies: ["supplementary", "supplementary"],
    conclusion: "con_ang",
  },
  con_complements: {
    name: "con_complements",
    title: "Congruent Complements",
    body: "If two angles are complementary to congruent angles, then the two angles are congruent.",
    dependencies: ["complementary", "complementary", "con_ang"],
    conclusion: "con_ang",
  },
  con_complements_same: {
    name: "con_complements_same",
    title: "Congruent Complements",
    body: "If two angles are complementary to the same angle, then the two angles are congruent.",
    dependencies: ["complementary", "complementary"],
    conclusion: "con_ang",
  },
  perp_bisector: {
    name: "perp_bisector",
    title: "Def. Perpendicular Bisector",
    body: "A line that is perpendicular to a segment and passes through its midpoint.",
    dependencies: ["perp", "midpt"],
    conclusion: "con_seg",
  },
  given: {
    name: "given",
    title: "Given",
    body: "",
    dependencies: ["__given_premise__"],
    conclusion: "__any__",
  },
  third_angle: {
    name: "third_angle",
    title: "Third Angle Theorem",
    body: "If two angles of one triangle are congruent to two angles of another triangle, then the third pair of angles are congruent.",
    dependencies: ["con_ang", "con_ang"],
    conclusion: "con_ang",
  },
  base_angle: {
    name: "base_angle",
    title: "Base Angle Theorem",
    body: "If two sides of a triangle are congruent, then the angles opposite the sides are congruent.",
    dependencies: ["con_seg"],
    conclusion: "con_ang",
  },
  base_angle_conv: {
    name: "base_angle_conv",
    title: "Base Angle Theorem (Converse)",
    body: "If two angles of a triangle are congruent, then the sides opposite those angles are congruent.",
    dependencies: ["con_ang"],
    conclusion: "con_seg",
  },
  equilat_equiang: {
    name: "equilat_equiang",
    title: "Equilateral Triangle Theorem",
    body: "If a triangle is equilateral, then it is also equiangular.",
    dependencies: ["equilateral"],
    conclusion: "equiangular",
  },
  equiang_equilat: {
    name: "equiang_equilat",
    title: "Equilateral Triangle Theorem (Converse)",
    body: "If a triangle is equiangular, then it is also equilateral.",
    dependencies: ["equiangular"],
    conclusion: "equilateral",
  },
  aa_sim: {
    name: "aa_sim",
    title: "AA Triangle Similarity",
    body: "If two angles of one triangle are congruent to two angles of another triangle, then the triangles are similar.",
    dependencies: ["con_ang_ref_allow", "con_ang_ref_allow"],
    conclusion: "sim_tri",
  },
  sss_sim: {
    name: "sss_sim",
    title: "SSS Triangle Similarity",
    body: "If three sides of one triangle are proportional to three sides of another triangle, then the triangles are similar.",
    dependencies: ["sim_seg", "sim_seg", "sim_seg"],
    conclusion: "sim_tri",
  },
  sas_sim: {
    name: "sas_sim",
    title: "SAS Triangle Similarity",
    body: "If two sides of one triangle are proportional to two sides of another triangle and their included angles are congruent, then the triangles are similar.",
    dependencies: ["sim_seg", "con_ang_ref_allow", "sim_seg"],
    conclusion: "sim_tri",
  },
  def_equiangular: {
    name: "def_equiangular",
    title: "Def. Equiangular",
    body: "A triangle is equiangular if all its angles are congruent.",
    dependencies: ["con_ang", "con_ang", "con_ang"],
    conclusion: "equiangular",
  },
  def_equilateral: {
    name: "def_equilateral",
    title: "Def. Equilateral",
    body: "A triangle is equilateral if all its sides are congruent.",
    dependencies: ["con_seg", "con_seg", "con_seg"],
    conclusion: "equilateral",
  },
  def_con_tri: {
    name: "def_con_tri",
    title: "Def. Congruent Triangles",
    body: "Two triangles are congruent if their corresponding sides and angles are congruent.",
    dependencies: [
      "con_seg",
      "con_seg",
      "con_seg",
      "con_ang",
      "con_ang",
      "con_ang",
    ],
    conclusion: "con_tri",
  },
  // parallelogram reasons
  def_parallelogram: {
    name: "def_parallelogram",
    title: "Def. Parallelogram",
    body: "A parallelogram is a quadrilateral with opposite sides that are parallel.",
    dependencies: ["para", "para"],
    conclusion: "parallelogram",
  },
  pgram_opp_sides: {
    name: "pgram_opp_sides",
    title: "Parallelogram Opposite Sides",
    body: "A parallelogram has opposite sides that are congruent.",
    dependencies: ["pgram_obj"],
    conclusion: "con_seg",
  },
  pgram_opp_sides_conv: {
    name: "pgram_opp_sides_conv",
    title: "Parallelogram Opposite Sides (Converse)",
    body: "If both pairs of opposite sides of a quadrilateral are congruent, then the quadrilateral is a parallelogram.",
    dependencies: ["con_seg", "con_seg"],
    conclusion: "parallelogram",
  },
  pgram_opp_angs: {
    name: "pgram_opp_angs",
    title: "Parallelogram Opposite Angles",
    body: "A parallelogram has opposite angles that are congruent.",
    dependencies: ["pgram_obj"],
    conclusion: "con_ang",
  },
  pgram_opp_angs_conv: {
    name: "pgram_opp_angs_conv",
    title: "Parallelogram Opposite Angles (Converse)",
    body: "If a quadrilateral has opposite angles that are congruent, then it is a parallelogram.",
    dependencies: ["con_ang", "con_ang"],
    conclusion: "parallelogram",
  },
  pgram_opp_side_para: {
    name: "pgram_opp_side_para",
    title: "Parallelogram Opposite Side Parallel",
    body: "If one pair of opposite sides of a quadrilateral are both parallel and congruent, then the quadrilateral is a parallelogram.",
    dependencies: ["con_seg", "para"],
    conclusion: "parallelogram",
  },
  // unimplemented reasons that will always return true for now
  pgram_consec_angs: {
    name: "pgram_consec_angs",
    title: "Parallelogram Consecutive Angles",
    body: "The consectutive angles of a parallelogram are supplementary.",
    dependencies: ["pgram_obj"],
    conclusion: "supplementary",
  },
  pgram_consec_angs_conv: {
    name: "pgram_consec_angs_conv",
    title: "Parallelogram Consecutive Angles (Converse)",
    body: "If an angle of a quadrilateral is supplementary to both its consecutive angles, then it is a parallelogram.",
    dependencies: ["supplementary", "supplementary"],
    conclusion: "parallelogram",
  },
  pgram_diag_bisect: {
    name: "pgram_diag_bisect",
    title: "Parallelogram Diagonal Bisect",
    body: "The diagonals of a parallelogram bisect each other.",
    dependencies: ["pgram_obj"],
    conclusion: "seg_bisect",
  },
  pgram_diag_bisect_conv: {
    name: "pgram_diag_bisect_conv",
    title: "Parallelogram Diagonal Bisect (Converse)",
    body: "If the diagonals of a quadrilateral bisect each other, then the quadrilateral is a parallelogram.",
    dependencies: ["seg_bisect", "seg_bisect"],
    conclusion: "parallelogram",
  },
  rectangle_pgram: {
    name: "rectangle_pgram",
    title: "Def. Rectangle",
    body: "A rectangle is a type of parallelogram that has four right angles. The opposite sides of a rectangle are equal in length.",
    dependencies: ["rectangle"],
    conclusion: "parallelogram",
  },
  rhombus_pgram: {
    name: "rhombus_pgram",
    title: "Def. Rhombus",
    body: "A rhombus is a type of parallelogram that has four congruent sides.",
    dependencies: ["rhombus"],
    conclusion: "parallelogram",
  },
  rect_diag_con: {
    name: "rect_diag_con",
    title: "Rectangle Diagonal Congruence",
    body: "The diagonals of a rectangle are congruent.",
    dependencies: ["rectangle"],
    conclusion: "con_seg",
  },
  rect_diag_con_conv: {
    name: "rect_diag_con_conv",
    title: "Rectangle Diagonal Congruence (Converse)",
    body: "If the diagonals of a parallelogram are congruent, then the parallelogram is a rectangle.",
    dependencies: ["con_seg", "pgram_obj"],
    conclusion: "rectangle",
  },
  rect_pgram_ang: {
    name: "rect_pgram_ang",
    title: "Rectangle Parallelogram Angle",
    body: "If one angle of a parallelogram is a right angle, then the parallelogram is a rectangle.",
    dependencies: ["right", "pgram_obj"],
    conclusion: "rectangle",
  },
  rhombus_diag_perp: {
    name: "rhombus_diag_perp",
    title: "Rhombus Diagonal Perpendicularity",
    body: "The diagonals of a rhombus are perpendicular.",
    dependencies: ["rhombus"],
    conclusion: "perp",
  },
  rhombus_diag_perp_conv: {
    name: "rhombus_diag_perp_conv",
    title: "Rhombus Diagonal Perpendicularity (Converse)",
    body: "If the diagonals of a parallelogram are perpendicular, then the quadrilateral is a rhombus.",
    dependencies: ["perp", "pgram_obj"],
    conclusion: "rhombus",
  },
  rhombus_opp_bisect_conv: {
    name: "rhombus_opp_bisect_conv",
    title: "Rhombus Opposite Diagonal Bisect (Converse)",
    body: "If one diagonal of a parallelogram bisects a pair of opposite angles, then the parallelogram is a rhombus.",
    dependencies: ["ang_bisect", "ang_bisect", "pgram_obj"],
    conclusion: "rhombus",
  },
  rhombus_opp_bisect: {
    name: "rhombus_opp_bisect",
    title: "Rhombus Opposite Diagonal Bisect",
    body: "Each diagonal of a rhombus bisects a pair of opposite angles.",
    dependencies: ["rhombus"],
    conclusion: "ang_bisect",
  },
  rhombus_consec_sides: {
    name: "rhombus_consec_sides",
    title: "Rhombus Consecutive Sides",
    body: "If one pair of consecutive sides of a parallelogram are congruent, then the parallelogram is a rhombus.",
    dependencies: ["pgram_obj", "con_seg"],
    conclusion: "rhombus",
  },
  kite_diag_perp: {
    name: "kite_diag_perp",
    title: "Kite Diagonal Perpendicularity",
    body: "If a quadrilateral is a kite, then its diagonals are perpendicular.",
    dependencies: ["kite_premise"],
    conclusion: "perp",
  },
  kite_opp_con_ang: {
    name: "kite_opp_con_ang",
    title: "Kite Opposite Congruent Angles",
    body: "If a quadrilateral is a kite, then exactly one pair of opposite angles are congruent. The congruent angles are the ones between the pairs of congruent sides.",
    dependencies: ["kite_premise"], // requires knowing what angles of the kite are congruent
    conclusion: "con_ang",
  },
  isos_trap_base_angs: {
    name: "isos_trap_base_angs",
    title: "Trapezoid with Congruent Base Angle",
    body: "If a trapezoid has one pair of congruent base angles, then the trapezoid is isosceles.",
    dependencies: ["con_ang", "trapezoid_premise"], // should be both premise and regular
    conclusion: "isos_trapezoid",
  },
  isos_trap_base_angs_conv: {
    name: "isos_trap_base_angs_conv",
    title: "Isosceles Trapezoid Base Angles",
    body: "If a quadrilateral is an isosceles trapezoid, then each pair of base angles are congruent.",
    dependencies: ["isos_trap_obj"], // should be BOTH isos_trapezoid_premise and isos_trapezoid
    conclusion: "con_ang",
  },
  isos_trap_con_diags: {
    name: "isos_trap_con_diags",
    title: "Isosceles Trapezoid Congruent Diagonals",
    body: "A trapezoid is isosceles if and only if its diagonals are congruent.",
    dependencies: ["con_seg", "trapezoid_premise"],
    conclusion: "isos_trapezoid",
  },
  tangent_perp: {
    name: "tangent_perp",
    title: "Tangent Perpendicularity",
    body: "A tangent to a circle is perpendicular to the radius at the point of tangency.",
    dependencies: ["tangent", "radius"],
    conclusion: "perp",
  },
  tangent_perp_conv: {
    name: "tangent_perp_conv",
    title: "Tangent Perpendicularity (Converse)",
    body: "If a line is perpendicular to a radius at the point of tangency, then the line is a tangent to the circle.",
    dependencies: ["perp", "radius"],
    conclusion: "tangent",
  },
  con_tangents_ext: {
    name: "con_tangents_ext",
    title: "Congruent Tangents from External Point",
    body: "If two segments are tangent to a circle from the same external point, then the segments are congruent.",
    dependencies: ["tangent", "tangent"],
    conclusion: "con_seg",
  },
  radius_chord_bisect: {
    name: "radius_chord_bisect",
    title: "Radius Chord Bisect",
    body: "If a radius of a circle is perpendicular to a chord, then it bisects the chord and its arc.",
    dependencies: ["perp", "radius", "chord"],
    conclusion: "seg_bisect", // todo arc bisect?
  },
  radius_chord_bisect_conv: {
    name: "radius_chord_bisect_conv",
    title: "Radius Chord Bisect (Converse)",
    body: "The perpendicular bisector of a chord is a radius of the circle.",
    dependencies: ["perp_bisector", "chord"],
    conclusion: "radius",
  },
  con_inscribed_angs: {
    name: "con_inscribed_angs",
    title: "Congruent Inscribed Angles",
    body: "If inscribed angles of a circle are subtended by the same chord or arc, then the angles are congruent.",
    dependencies: ["inscribed_angle", "inscribed_angle"],
    conclusion: "con_ang",
  },
  // still implementing cutoff
  // inscribed_quad: {
  //   // todo need a quadrilateral and circle statement to work with this
  //   name: "inscribed_quad",
  //   title: "Inscribed Quadrilateral",
  //   body: "If a quadrilateral is inscribed in a circle, then its opposite angles are supplementary.",
  //   dependencies: [""],
  //   conclusion: "supplementary",
  // },
  incenter: {
    name: "incenter",
    title: "Incenter Theorem",
    body: "The incenter of a triangle is the point where the angle bisectors of the angles intersect. It is equidistant from the sides of the triangle.",
    dependencies: ["ang_bisect", "ang_bisect", "ang_bisect"],
    conclusion: "incenter",
  },
  con_seg_transitive: {
    name: "con_seg_transitive",
    title: "Transitive Property of Congruence",
    body: "If two geometric figures are congruent to the same figure, then they are congruent to each other.",
    dependencies: ["con_seg", "con_seg"],
    conclusion: "con_seg",
  },
  con_ang_transitive: {
    name: "con_ang_transitive",
    title: "Transitive Property of Congruence",
    body: "If two geometric figures are congruent to the same figure, then they are congruent to each other.",
    dependencies: ["con_ang", "con_ang"],
    conclusion: "con_ang",
  },
  con_tri_transitive: {
    name: "con_tri_transitive",
    title: "Transitive Property of Congruence",
    body: "If two geometric figures are congruent to the same figure, then they are congruent to each other.",
    dependencies: ["con_tri", "con_tri"],
    conclusion: "con_tri",
  },
  // con_arc_transitive: {
  //   name: "con_arc_transitive",
  //   title: "Transitive Property of Congruence",
  //   body: "If two geometric figures are congruent to the same figure, then they are congruent to each other.",
  //   dependencies: ["con_arc", "con_arc"],
  //   conclusion: "con_arc",
  // },
} as const;
